export enum Tools {
	GetThread = "getThread",
	ComposeEmail = "composeEmail",
	DeleteEmail = "deleteEmail",
	MarkThreadsRead = "markThreadsRead",
	MarkThreadsUnread = "markThreadsUnread",
	ModifyLabels = "modifyLabels",
	GetUserLabels = "getUserLabels",
	SendEmail = "sendEmail",
	CreateLabel = "createLabel",
	BulkDelete = "bulkDelete",
	BulkArchive = "bulkArchive",
	DeleteLabel = "deleteLabel",
	AskZeroMailbox = "askZeroMailbox",
	AskZeroThread = "askZeroThread",
	WebSearch = "webSearch",
	InboxRag = "inboxRag",
	BuildGmailSearchQuery = "buildGmailSearchQuery",
}
